### ISSUE TITLE
Crash if there's no tag in the repo (releaseman --ci create-changelog --version=v0.9.0)

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-tools/releaseman#6]
```
$ releaseman --ci create-changelog --version=v0.9.0

INFO[14:42:53] Your configuration:
INFO[14:42:53]  * Development branch: master
INFO[14:42:53]  * Release version: v0.9.0
INFO[14:42:53]  * Changelog path: CHANGELOG.md


panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x7051c]

goroutine 1 [running]:
panic(0x450200, 0xc8200160d0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/bitrise-tools/releaseman/cli.printCollectingCommits(0x0, 0xc8200e4680, 0x6)
	/Users/viktorbenei/develop/go/src/github.com/bitrise-tools/releaseman/cli/utility.go:411 +0x4c
github.com/bitrise-tools/releaseman/cli.generateChangelog(0xc8200e41b0, 0x6, 0xc8200e41e0, 0x6, 0xc8200e4680, 0x6, 0xc8200e4210, 0xc, 0xc8200c4b00, 0xfb, ...)
	/Users/viktorbenei/develop/go/src/github.com/bitrise-tools/releaseman/cli/command_create_changelog.go:80 +0x319
github.com/bitrise-tools/releaseman/cli.createChangelog(0xc820090dc0)
	/Users/viktorbenei/develop/go/src/github.com/bitrise-tools/releaseman/cli/command_create_changelog.go:147 +0x6d0
github.com/bitrise-tools/releaseman/vendor/github.com/codegangsta/cli.Command.Run(0x5268a0, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x521740, 0x10, 0x0, ...)
	/Users/viktorbenei/develop/go/src/github.com/bitrise-tools/releaseman/vendor/github.com/codegangsta/cli/command.go:174 +0x1399
github.com/bitrise-tools/releaseman/vendor/github.com/codegangsta/cli.(*App).Run(0xc820090b40, 0xc82000a3c0, 0x4, 0x4, 0x0, 0x0)
	/Users/viktorbenei/develop/go/src/github.com/bitrise-tools/releaseman/vendor/github.com/codegangsta/cli/app.go:187 +0x112b
github.com/bitrise-tools/releaseman/cli.Run()
	/Users/viktorbenei/develop/go/src/github.com/bitrise-tools/releaseman/cli/cli.go:51 +0x199
main.main()
	/Users/viktorbenei/develop/go/src/github.com/bitrise-tools/releaseman/main.go:16 +0x14
```

**Comment by lpusok** [comment]
Closing as repo deprecated.
